version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "daily"
    assignees:
      - "vincejv"
    labels:
      - "dependencies"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "daily"
    assignees:
      - "vincejv"
    labels:
      - "dependencies"
      - "ci-cd"
    open-pull-requests-limit: 20