quarkus:
  http:
    port: ${PORT:8080}
  arc:
    exclude-types:
      - com.abavilla.fpi.sms.ext.rest.*
  mongodb:
    connection-string:
      ${MONGO_CONN_STRING:mongodb://localhost}
    database: ${DB_NAME}
  liquibase-mongodb:
    migrate-at-start: true
    change-log: db/changeLog.xml
    validate-on-migrate: true
    clean-at-start: false
  rest-client:
    login-api: # required by app-to-app auth
      url: ${LOGIN_BASE_URI}
      scope: jakarta.inject.Singleton
    user-api:
      url: ${USER_BASE_URI}
      scope: jakarta.inject.Singleton
  oidc:
    auth-server-url: ${OIDC_AUTH_URL:https://localhost:8543/realms/quarkus}
    client-id: ${OIDC_CLIENT_ID:backend-api}
    credentials:
      secret: ${OIDC_SECRET:AABBCC}
    tls:
      verification: none
  keycloak:
    policy-enforcer:
      enable: true
      paths:
        dlr-access:
          path: /fpi/sms/dlr/*
          enforcement-mode: DISABLED
  native:
    resources:
      includes:
        com/google/i18n/phonenumbers/data/**,com/google/i18n/phonenumbers/carrier/data/**

fpi:
  app-to-app:
    auth:
      username: ${FPI_APP_TO_APP_USERN:username}
      password: ${FPI_APP_TO_APP_PASSW:password}
  webhook:
    dlr:
      api-key: ${FPI_DLR_WEBHOOK_KEY:FPIDLRAABBBDDCCCQQQ}
    mo:
      api-key: ${FPI_MO_WEBHOOK_KEY:FPIDLRAABBBDDCCCQQQ}

ph:
  com:
    m360:
      base-url: ${M360_API_URL}
      api-key: ${SMS_API_KEY:123456789}
      api-secret: ${SMS_SECRET:123456789}
      sender-id: ${SMS_SID:ABCDE}
