name: PR Reviewer
on:
  issue_comment:
    types: [ created, edited ]
env:
  REPOSITORY_OWNER: vincejv
  REPOSITORY_BOT: fpibot
jobs:
  review:
    name: Perform review
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request
        if: ${{ github.actor == env.REPOSITORY_OWNER && contains(github.event.comment.body, format('@{0}', env.REPOSITORY_BOT)) }}
        uses: hmarr/auto-approve-action@v3
        with:
          pull-request-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.FPI_BOT_TOKEN }}
          review-message: ${{ format('Hi @{0}, your code changes are approved! 🥳', github.event.issue.user.login) }}